package me.infamous.mob_vote_five.client.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class ArmadilloAnimation {

	public static final AnimationDefinition ARMADILLO_IDLE = AnimationDefinition.Builder.withLength(4.48f).looping()
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2f, KeyframeAnimations.degreeVec(0f, 25f, 25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.4f, KeyframeAnimations.degreeVec(0f, 25f, 25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.64f, KeyframeAnimations.degreeVec(0f, -25f, -5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.64f, KeyframeAnimations.degreeVec(0f, -25f, -5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.92f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.48f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.44f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.56f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.68f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.24f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.68f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.8f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.24f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.36f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.8f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.92f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.36f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.48f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ball",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
	public static final AnimationDefinition ARMADILLO_WALK = AnimationDefinition.Builder.withLength(0.96f).looping()
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.96f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(5f, -5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(5f, 5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.96f, KeyframeAnimations.degreeVec(5f, -5f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-5f, 5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(-5f, -5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.96f, KeyframeAnimations.degreeVec(-5f, 5f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg1",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 1f, -0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.96f, KeyframeAnimations.posVec(0f, 0f, 0.5f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg1",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(15.05f, 4.83f, 1.3f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(0.03f, -0.09f, 0.65f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(-15.05f, 4.83f, -1.3f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(-0.03f, -0.09f, -0.65f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.96f, KeyframeAnimations.degreeVec(15.05f, 4.83f, 1.3f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg2",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 0f, 0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.96f, KeyframeAnimations.posVec(0f, 0f, -0.5f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-15.05f, 4.83f, -1.3f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(-0.03f, -0.09f, -0.65f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(15.05f, 4.83f, 1.3f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(0.03f, -0.09f, 0.65f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.96f, KeyframeAnimations.degreeVec(-15.05f, 4.83f, -1.3f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg3",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, -0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 1f, 0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.96f, KeyframeAnimations.posVec(0f, 1f, -0.5f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-15.05f, 4.83f, -1.3f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(-0.03f, -0.09f, -0.65f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(15.12f, -7.24f, -1.95f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(0.06f, -1.12f, -0.97f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.96f, KeyframeAnimations.degreeVec(-15.05f, 4.83f, -1.3f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg4",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, 0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 1f, -0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.96f, KeyframeAnimations.posVec(0f, 1f, 0.5f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(15.05f, 4.83f, 1.3f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(0.03f, 2.41f, 0.65f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(-15.05f, -4.83f, 1.3f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(-0.03f, 0.09f, 0.65f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.96f, KeyframeAnimations.degreeVec(15.05f, 4.83f, 1.3f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.96f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("ball",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
	public static final AnimationDefinition ARMADILLO_HIDE = AnimationDefinition.Builder.withLength(0.72f)
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.posVec(0f, 6f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2f, KeyframeAnimations.scaleVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg1",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(-115f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ball",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.2f, KeyframeAnimations.posVec(0f, 8f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.44f, KeyframeAnimations.posVec(0f, 8f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.posVec(0f, 2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ball",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.scaleVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
	public static final AnimationDefinition ARMADILLO_HIDE_IDLE = AnimationDefinition.Builder.withLength(4.48f).looping()
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ball",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.48f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("ball",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition ARMADILLO_ROLL = AnimationDefinition.Builder.withLength(1.28f).looping()
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ball",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.16f, KeyframeAnimations.posVec(0f, 3.25f, 6f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.32f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 3.25f, 6f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.64f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8f, KeyframeAnimations.posVec(0f, 2.75f, 6f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.96f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.12f, KeyframeAnimations.posVec(-1f, 2.64f, 6f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("ball",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(180f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.96f, KeyframeAnimations.degreeVec(270f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(360f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition ARMADILLO_APPEAR = AnimationDefinition.Builder.withLength(0.6f)
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, -3f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.12f, KeyframeAnimations.posVec(0f, -3f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.28f, KeyframeAnimations.posVec(0f, 14f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.44f, KeyframeAnimations.posVec(0f, 14f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.44f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("body",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.12f, KeyframeAnimations.scaleVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.6f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.12f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.44f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ear1",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.44f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ear2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.44f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg1",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.12f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(45f, 0f, 25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.44f, KeyframeAnimations.degreeVec(45f, 0f, 25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.12f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(45f, 0f, -25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.44f, KeyframeAnimations.degreeVec(45f, 0f, -25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.12f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(-25f, 0f, 25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.44f, KeyframeAnimations.degreeVec(-25f, 0f, 25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.12f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(-25f, 0f, -25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.44f, KeyframeAnimations.degreeVec(-25f, 0f, -25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-115f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.12f, KeyframeAnimations.degreeVec(-115f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(85f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.44f, KeyframeAnimations.degreeVec(85f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.6f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("ball",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.12f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.16f, KeyframeAnimations.scaleVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
}