package me.infamous.mob_vote_five.client.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class CrabAnimation{

	public static final AnimationDefinition CRAB_WALK = AnimationDefinition.Builder.withLength(0.64f).looping()
			.addAnimation("crab",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("crab",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 0f, -5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg1",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.posVec(-1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.posVec(-0.75f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg1",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-3.45f, 25.61f, 20.28f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(3.77f, 50.13f, 9.56f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(-0.21f, 37.88f, 29.85f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(18.68f, 52.55f, 50.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(-3.45f, 25.61f, 20.28f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("sub_leg1",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -45f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 0f, -32.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, -35f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, -45f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg2",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(1.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.posVec(0.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.posVec(0.25f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.posVec(1.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(7.96f, -41.07f, -52.92f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(-1.51f, -32f, -7.76f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(8.35f, -52.06f, -9.9f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(-2.23f, -32.5f, -22.77f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(8.22f, -40.72f, -55.41f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("sub_leg2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 55f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, 17.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 0f, 25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 50f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, 30f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg3",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(-0.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.posVec(-0.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.posVec(-0.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.posVec(-0.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.posVec(-0.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(10.45f, 24.69f, 24.17f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(2.24f, -1.49f, 50.4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(15.4f, 22.31f, 21.53f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("sub_leg3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -15f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 0f, -55f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, -42.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, -15f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg4",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.posVec(0.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.posVec(0.75f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.posVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(8.74f, -18.06f, -26.39f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(-0.29f, -1.23f, -42.23f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(17.1f, -21.02f, -25.41f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(-0.83f, -0.96f, -14.72f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(8.74f, -18.06f, -26.39f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("sub_leg4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, 52.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 0f, 55f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 27.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, 25f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg5",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(-1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.posVec(-1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.posVec(-0.75f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.posVec(-1f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg5",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(4.61f, -20.71f, 30.58f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(20.05f, 5.12f, 31.19f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(4.87f, -27.49f, 31.88f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(16.15f, 3.46f, 16.86f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(4.61f, -20.71f, 30.58f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("sub_leg5",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -15f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(-3.21f, 1.86f, -51.03f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 0f, -37.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, -27.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, -15f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg6",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.posVec(1.25f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.posVec(0.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg6",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(9.85f, -9.14f, -14f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(-0.17f, 32.91f, -14.87f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(26.87f, 5.56f, -42.67f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(0.81f, 33.07f, -42.38f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(9.85f, -9.14f, -14f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("sub_leg6",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, 30f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(0f, 0f, 22.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 55f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, -2.5f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
	public static final AnimationDefinition CRAB_IDLE = AnimationDefinition.Builder.withLength(7.56f).looping()
			.addAnimation("crab",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.28f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.92f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.2f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.84f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.48f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.12f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.76f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.4f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("crab",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.56f, KeyframeAnimations.degreeVec(12.69f, -9.76f, -2.19f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.88f, KeyframeAnimations.degreeVec(12.69f, -9.76f, -2.19f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7f, KeyframeAnimations.degreeVec(-5.5f, -10.88f, -12.29f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.12f, KeyframeAnimations.degreeVec(12.69f, -9.76f, -2.19f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.24f, KeyframeAnimations.degreeVec(-5.5f, -10.88f, -12.29f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.36f, KeyframeAnimations.degreeVec(12.69f, -9.76f, -2.19f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("eye1",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(1.6f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.72f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.84f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.96f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.08f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.2f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.16f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.28f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.52f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.64f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.76f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("eye2",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(1.6f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.72f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.84f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.96f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.08f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.2f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.16f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.28f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.52f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.64f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.76f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("great_pincer",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.28f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.92f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.2f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.84f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.48f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.12f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.76f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.4f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.56f, KeyframeAnimations.posVec(-0.5f, 1.25f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.88f, KeyframeAnimations.posVec(-0.5f, 1.25f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7f, KeyframeAnimations.posVec(0.25f, 3.5f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.12f, KeyframeAnimations.posVec(-0.5f, 1.25f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.24f, KeyframeAnimations.posVec(0.25f, 3.5f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.36f, KeyframeAnimations.posVec(-0.5f, 1.25f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("great_pincer",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.56f, KeyframeAnimations.degreeVec(-21.55f, -27.77f, 34.1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.88f, KeyframeAnimations.degreeVec(-21.55f, -27.77f, 34.1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7f, KeyframeAnimations.degreeVec(-133.22f, -30.41f, 119.8f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.12f, KeyframeAnimations.degreeVec(-21.55f, -27.77f, 34.1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.24f, KeyframeAnimations.degreeVec(-133.22f, -30.41f, 119.8f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.36f, KeyframeAnimations.degreeVec(-21.55f, -27.77f, 34.1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("pincer",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.posVec(0.5f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.28f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.92f, KeyframeAnimations.posVec(0.5f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.2f, KeyframeAnimations.posVec(0.5f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.84f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.48f, KeyframeAnimations.posVec(0.5f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.12f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.76f, KeyframeAnimations.posVec(0.5f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.4f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.56f, KeyframeAnimations.posVec(0f, 1.25f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.88f, KeyframeAnimations.posVec(0f, 1.25f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.12f, KeyframeAnimations.posVec(0f, 1.25f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.24f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.36f, KeyframeAnimations.posVec(0f, 1.25f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("pincer",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("leg1",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.92f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.2f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.48f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.76f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.56f, KeyframeAnimations.degreeVec(-21.38f, 17.31f, 31.48f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.88f, KeyframeAnimations.degreeVec(-21.38f, 17.31f, 31.48f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7f, KeyframeAnimations.degreeVec(-4.96f, 5.02f, 33.46f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.12f, KeyframeAnimations.degreeVec(-21.38f, 17.31f, 31.48f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.24f, KeyframeAnimations.degreeVec(-4.96f, 5.02f, 33.46f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.36f, KeyframeAnimations.degreeVec(-21.38f, 17.31f, 31.48f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("sub_leg1",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(-7.5f, 0f, -5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.92f, KeyframeAnimations.degreeVec(-7.5f, 0f, -5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.2f, KeyframeAnimations.degreeVec(-7.5f, 0f, -5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.48f, KeyframeAnimations.degreeVec(-7.5f, 0f, -5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.76f, KeyframeAnimations.degreeVec(-7.5f, 0f, -5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.56f, KeyframeAnimations.degreeVec(0f, 0f, -32.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.88f, KeyframeAnimations.degreeVec(0f, 0f, -32.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7f, KeyframeAnimations.degreeVec(0f, 0f, -45f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.12f, KeyframeAnimations.degreeVec(0f, 0f, -32.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.24f, KeyframeAnimations.degreeVec(0f, 0f, -45f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.36f, KeyframeAnimations.degreeVec(0f, 0f, -32.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.92f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.2f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.48f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.76f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.56f, KeyframeAnimations.degreeVec(-20.79f, -19.99f, -25.23f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.88f, KeyframeAnimations.degreeVec(-20.79f, -19.99f, -25.23f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7f, KeyframeAnimations.degreeVec(2.26f, 1.26f, 9.69f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.12f, KeyframeAnimations.degreeVec(-20.79f, -19.99f, -25.23f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.24f, KeyframeAnimations.degreeVec(2.26f, 1.26f, 9.69f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.36f, KeyframeAnimations.degreeVec(-20.79f, -19.99f, -25.23f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("sub_leg2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(-7.5f, 0f, 5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.92f, KeyframeAnimations.degreeVec(-7.5f, 0f, 5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.2f, KeyframeAnimations.degreeVec(-7.5f, 0f, 5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.48f, KeyframeAnimations.degreeVec(-7.5f, 0f, 5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.76f, KeyframeAnimations.degreeVec(-7.5f, 0f, 5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.56f, KeyframeAnimations.degreeVec(0f, 0f, 35f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.88f, KeyframeAnimations.degreeVec(0f, 0f, 35f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7f, KeyframeAnimations.degreeVec(0f, 0f, 42.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.12f, KeyframeAnimations.degreeVec(0f, 0f, 35f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.24f, KeyframeAnimations.degreeVec(0f, 0f, 42.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.36f, KeyframeAnimations.degreeVec(0f, 0f, 35f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.92f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.2f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.48f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.76f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.56f, KeyframeAnimations.degreeVec(-9.22f, 12.07f, 15.35f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.88f, KeyframeAnimations.degreeVec(-9.22f, 12.07f, 15.35f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7f, KeyframeAnimations.degreeVec(11.12f, 9.52f, 30.4f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.12f, KeyframeAnimations.degreeVec(-9.22f, 12.07f, 15.35f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.24f, KeyframeAnimations.degreeVec(11.12f, 9.52f, 30.4f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.36f, KeyframeAnimations.degreeVec(-9.22f, 12.07f, 15.35f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("sub_leg3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.92f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.2f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.48f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.76f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.56f, KeyframeAnimations.degreeVec(0f, 0f, -30f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.88f, KeyframeAnimations.degreeVec(0f, 0f, -30f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7f, KeyframeAnimations.degreeVec(0f, 0f, -22.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.12f, KeyframeAnimations.degreeVec(0f, 0f, -30f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.24f, KeyframeAnimations.degreeVec(0f, 0f, -22.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.36f, KeyframeAnimations.degreeVec(0f, 0f, -30f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.92f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.2f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.48f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.76f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.56f, KeyframeAnimations.degreeVec(-9.5f, -14.89f, -12.63f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.88f, KeyframeAnimations.degreeVec(-9.5f, -14.89f, -12.63f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7f, KeyframeAnimations.degreeVec(5.43f, 6.08f, 3.25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.12f, KeyframeAnimations.degreeVec(-9.5f, -14.89f, -12.63f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.24f, KeyframeAnimations.degreeVec(5.43f, 6.08f, 3.25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.36f, KeyframeAnimations.degreeVec(-9.5f, -14.89f, -12.63f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("sub_leg4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.92f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.2f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.48f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.76f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.56f, KeyframeAnimations.degreeVec(0f, 0f, 40f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.88f, KeyframeAnimations.degreeVec(0f, 0f, 40f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7f, KeyframeAnimations.degreeVec(0f, 0f, 32.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.12f, KeyframeAnimations.degreeVec(0f, 0f, 40f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.24f, KeyframeAnimations.degreeVec(0f, 0f, 32.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.36f, KeyframeAnimations.degreeVec(0f, 0f, 40f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg5",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(6.72f, -0.36f, 13.01f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.92f, KeyframeAnimations.degreeVec(6.72f, -0.36f, 13.01f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.2f, KeyframeAnimations.degreeVec(6.72f, -0.36f, 13.01f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.48f, KeyframeAnimations.degreeVec(6.72f, -0.36f, 13.01f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.76f, KeyframeAnimations.degreeVec(6.72f, -0.36f, 13.01f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.56f, KeyframeAnimations.degreeVec(-10f, 12.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.88f, KeyframeAnimations.degreeVec(-10f, 12.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7f, KeyframeAnimations.degreeVec(39.97f, 8.47f, 56.06f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.12f, KeyframeAnimations.degreeVec(-10f, 12.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.24f, KeyframeAnimations.degreeVec(39.97f, 8.47f, 56.06f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.36f, KeyframeAnimations.degreeVec(-10f, 12.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("sub_leg5",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.92f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.2f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.48f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.76f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.56f, KeyframeAnimations.degreeVec(0f, 0f, -32.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.88f, KeyframeAnimations.degreeVec(0f, 0f, -32.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7f, KeyframeAnimations.degreeVec(0f, 0f, -30f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.12f, KeyframeAnimations.degreeVec(0f, 0f, -32.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.24f, KeyframeAnimations.degreeVec(0f, 0f, -30f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.36f, KeyframeAnimations.degreeVec(0f, 0f, -32.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg6",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(6.72f, 0.36f, -13.01f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.92f, KeyframeAnimations.degreeVec(6.72f, 0.36f, -13.01f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.2f, KeyframeAnimations.degreeVec(6.72f, 0.36f, -13.01f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.48f, KeyframeAnimations.degreeVec(6.72f, 0.36f, -13.01f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.76f, KeyframeAnimations.degreeVec(6.72f, 0.36f, -13.01f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.56f, KeyframeAnimations.degreeVec(-20.14f, -9.48f, 17.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.88f, KeyframeAnimations.degreeVec(-20.14f, -9.48f, 17.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7f, KeyframeAnimations.degreeVec(16.66f, -1.79f, -6.46f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.12f, KeyframeAnimations.degreeVec(-20.14f, -9.48f, 17.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.24f, KeyframeAnimations.degreeVec(16.66f, -1.79f, -6.46f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.36f, KeyframeAnimations.degreeVec(-20.14f, -9.48f, 17.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("sub_leg6",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.92f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.2f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.48f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.76f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.56f, KeyframeAnimations.degreeVec(0f, 0f, 12.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.88f, KeyframeAnimations.degreeVec(0f, 0f, 12.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7f, KeyframeAnimations.degreeVec(0f, 0f, 25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.12f, KeyframeAnimations.degreeVec(0f, 0f, 12.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.24f, KeyframeAnimations.degreeVec(0f, 0f, 25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.36f, KeyframeAnimations.degreeVec(0f, 0f, 12.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition CRAB_GREETING = AnimationDefinition.Builder.withLength(1f)
			.addAnimation("crab",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.36f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.52f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.68f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.84f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("crab",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(-6.95f, -14.22f, -17.29f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.36f, KeyframeAnimations.degreeVec(-3.8f, -15.47f, -9.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(-6.95f, -14.22f, -17.29f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.68f, KeyframeAnimations.degreeVec(-3.8f, -15.47f, -9.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(-6.95f, -14.22f, -17.29f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("great_pincer",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2f, KeyframeAnimations.posVec(1f, 3.75f, -0.75f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.36f, KeyframeAnimations.posVec(2f, 1.25f, -1.75f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.52f, KeyframeAnimations.posVec(1f, 3.75f, -0.75f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.68f, KeyframeAnimations.posVec(2f, 1.25f, -1.75f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.84f, KeyframeAnimations.posVec(1f, 3.75f, -0.75f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("great_pincer",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(202.68f, 15.03f, -217.92f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.36f, KeyframeAnimations.degreeVec(161.15f, -6.82f, -147.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(202.68f, 15.03f, -217.92f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.68f, KeyframeAnimations.degreeVec(161.15f, -6.82f, -147.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(202.68f, 15.03f, -217.92f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("great_pincer_part1",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, 5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("great_pincer_part2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("pincer",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2f, KeyframeAnimations.posVec(0.25f, 0f, -0.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.36f, KeyframeAnimations.posVec(0.25f, 0f, -0.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.52f, KeyframeAnimations.posVec(0.25f, 0f, -0.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.68f, KeyframeAnimations.posVec(0.25f, 0f, -0.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.84f, KeyframeAnimations.posVec(0.25f, 0f, -0.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("pincer",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(5.64f, 20.05f, 21.65f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.36f, KeyframeAnimations.degreeVec(5.64f, 20.05f, 21.65f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(5.64f, 20.05f, 21.65f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.68f, KeyframeAnimations.degreeVec(5.64f, 20.05f, 21.65f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(5.64f, 20.05f, 21.65f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("pincer_part1",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("pincer_part2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, 15f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(0f, 0f, 15f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, 15f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg1",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.posVec(-0.75f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.posVec(-0.75f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.posVec(-0.75f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg1",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(9.6f, 16.9f, 12.63f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.36f, KeyframeAnimations.degreeVec(6.99f, 17.66f, 4.8f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(9.6f, 16.9f, 12.63f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.68f, KeyframeAnimations.degreeVec(6.99f, 17.66f, 4.8f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(9.6f, 16.9f, 12.63f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("sub_leg1",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.36f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.68f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg2",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.2f, KeyframeAnimations.posVec(1.25f, 0f, -0.25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.posVec(1.25f, 0f, -0.25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.posVec(1.25f, 0f, -0.25f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(49.2f, 2.43f, 69.34f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.36f, KeyframeAnimations.degreeVec(31.88f, 17.33f, 45.19f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(49.2f, 2.43f, 69.34f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.68f, KeyframeAnimations.degreeVec(31.88f, 17.33f, 45.19f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(49.2f, 2.43f, 69.34f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("sub_leg2",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, 10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg3",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.2f, KeyframeAnimations.posVec(-0.75f, 0.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.posVec(-0.75f, 0.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.posVec(-0.75f, 0.5f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(10.4f, 11.71f, 20.99f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.36f, KeyframeAnimations.degreeVec(4.51f, 13.67f, 5.75f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(10.4f, 11.71f, 20.99f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.68f, KeyframeAnimations.degreeVec(4.51f, 13.67f, 5.75f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(10.4f, 11.71f, 20.99f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("sub_leg3",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, -15f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.36f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(0f, 0f, -15f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.68f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, -15f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg4",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.2f, KeyframeAnimations.posVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.posVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.posVec(1f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(15.4f, 6.67f, 40.24f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.36f, KeyframeAnimations.degreeVec(10.71f, 10.18f, 25.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(15.4f, 6.67f, 40.24f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.68f, KeyframeAnimations.degreeVec(10.71f, 10.18f, 25.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(15.4f, 6.67f, 40.24f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("sub_leg4",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg5",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.2f, KeyframeAnimations.posVec(-1.25f, 0.5f, 0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.posVec(-1.25f, 0.5f, 0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.posVec(-1.25f, 0.5f, 0.5f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg5",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(34.5f, 11.73f, 55.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.36f, KeyframeAnimations.degreeVec(23.22f, 21.34f, 31.72f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(34.5f, 11.73f, 55.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.68f, KeyframeAnimations.degreeVec(23.22f, 21.34f, 31.72f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(34.5f, 11.73f, 55.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("sub_leg5",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, -27.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.36f, KeyframeAnimations.degreeVec(0f, 0f, -25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(0f, 0f, -27.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.68f, KeyframeAnimations.degreeVec(0f, 0f, -25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, -27.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg6",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.2f, KeyframeAnimations.posVec(0.5f, 0f, 0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.posVec(0.5f, 0f, 0.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.posVec(0.5f, 0f, 0.5f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("leg6",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(3.57f, -4.21f, 29.77f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.36f, KeyframeAnimations.degreeVec(0.86f, 0.3f, 16.97f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(3.57f, -4.21f, 29.77f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.68f, KeyframeAnimations.degreeVec(0.86f, 0.3f, 16.97f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(3.57f, -4.21f, 29.77f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("sub_leg6",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.2f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.36f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.52f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.68f, KeyframeAnimations.degreeVec(0f, 0f, 2.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, -10f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR))).build();
}