package me.infamous.mob_vote_five.client.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class PenguinAnimation {

	public static final AnimationDefinition PENGUIN_IDLE = AnimationDefinition.Builder.withLength(9.84f).looping()
			.addAnimation("penguin",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, -0.5f, -0.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.04f, KeyframeAnimations.posVec(0f, -0.5f, -0.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.76f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.48f, KeyframeAnimations.posVec(0f, -0.5f, -0.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.8f, KeyframeAnimations.posVec(0f, -0.5f, -0.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.52f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.24f, KeyframeAnimations.posVec(0f, -0.5f, -0.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.56f, KeyframeAnimations.posVec(0f, -0.5f, -0.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.28f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.8f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("penguin",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.04f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.76f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.48f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.8f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.52f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.24f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.56f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.8f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fin_right",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.04f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.76f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.48f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.8f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.52f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.24f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.56f, KeyframeAnimations.degreeVec(0f, 0f, -17.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.28f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.8f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("feet_right",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.04f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.76f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.48f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.52f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.24f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.56f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.28f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.8f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("feet_right",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.04f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.76f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.48f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.52f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.24f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.56f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.8f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("feet_left",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.04f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.76f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.48f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.52f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.24f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.56f, KeyframeAnimations.posVec(0f, 0.25f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.28f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.8f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("feet_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.04f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.76f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.48f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.52f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.24f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(4.56f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.8f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("fin_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 7.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(0f, 0f, 17.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.04f, KeyframeAnimations.degreeVec(0f, 0f, 17.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.76f, KeyframeAnimations.degreeVec(0f, 0f, 7.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.48f, KeyframeAnimations.degreeVec(0f, 0f, 17.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.8f, KeyframeAnimations.degreeVec(0f, 0f, 17.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.52f, KeyframeAnimations.degreeVec(0f, 0f, 7.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.24f, KeyframeAnimations.degreeVec(0f, 0f, 17.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.56f, KeyframeAnimations.degreeVec(0f, 0f, 17.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.28f, KeyframeAnimations.degreeVec(0f, 0f, 7.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.8f, KeyframeAnimations.degreeVec(0f, 0f, 7.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.04f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.76f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.48f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.8f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.52f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.24f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(4.56f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(5.8f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(6.24f, KeyframeAnimations.degreeVec(-0.5f, 12.5f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.52f, KeyframeAnimations.degreeVec(-0.5f, 12.5f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.64f, KeyframeAnimations.degreeVec(0.33f, -37.5f, 3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(7.88f, KeyframeAnimations.degreeVec(0.5f, -47.5f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(9f, KeyframeAnimations.degreeVec(0.5f, -47.5f, 4f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(9.24f, KeyframeAnimations.degreeVec(-0.81f, 7.19f, -1.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(9.32f, KeyframeAnimations.degreeVec(-1f, 15f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(9.48f, KeyframeAnimations.degreeVec(-1f, 15f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(9.84f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("eye_right",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.72f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.84f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.96f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.68f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.52f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.64f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.36f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("eye_left",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.72f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.84f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.96f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.68f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.4f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.52f, KeyframeAnimations.scaleVec(1f, 0f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(5.64f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(7.36f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition PENGUIN_SWIMMING = AnimationDefinition.Builder.withLength(0.8f).looping()
			.addAnimation("penguin",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.posVec(0f, 3f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.posVec(0f, 3f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8f, KeyframeAnimations.posVec(0f, -1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("penguin",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(110f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.degreeVec(65f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(65f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8f, KeyframeAnimations.degreeVec(110f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("fin_right",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, -3f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.posVec(0f, -3f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8f, KeyframeAnimations.posVec(0f, -3f, -1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fin_right",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(25f, 20f, -35f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, -90f, -90f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.degreeVec(-25f, -145f, -115f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(-90f, -45f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8f, KeyframeAnimations.degreeVec(25f, 20f, -35f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("feet_right",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4f, KeyframeAnimations.posVec(0f, -1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("feet_right",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4f, KeyframeAnimations.degreeVec(135f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("feet_left",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8f, KeyframeAnimations.posVec(0f, -1f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("feet_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(115f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.4f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.8f, KeyframeAnimations.degreeVec(115f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("fin_left",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, -3f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.posVec(0f, -3f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8f, KeyframeAnimations.posVec(0f, -3f, -1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fin_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(25f, -20f, 35f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, 90f, 90f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.degreeVec(-25f, 145f, 115f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(-90f, 45f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8f, KeyframeAnimations.degreeVec(25f, -20f, 35f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 3f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8f, KeyframeAnimations.posVec(0f, 3f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-125f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.8f, KeyframeAnimations.degreeVec(-125f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
	public static final AnimationDefinition PENGUIN_WALK = AnimationDefinition.Builder.withLength(1.12f).looping()
			.addAnimation("penguin",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 17.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(0f, 0f, 12.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(0f, -17.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, -12.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, 17.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fin_right",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(0f, 0f, -22.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, -22.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("feet_right",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.posVec(-0.5f, 0.25f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.84f, KeyframeAnimations.posVec(0f, 0.5f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.12f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("feet_right",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-10f, -17.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(0f, 0f, -12.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(7.5f, 17.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(-10f, 0f, 12.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.12f, KeyframeAnimations.degreeVec(-10f, -17.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("feet_left",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.posVec(0f, 0.5f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.84f, KeyframeAnimations.posVec(0.5f, 0.25f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.12f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("feet_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(7.5f, -17.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(-10f, 0f, -12.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(-10f, 17.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, 12.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.12f, KeyframeAnimations.degreeVec(7.5f, -17.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fin_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(0f, 0f, 22.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, 22.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -17.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.28f, KeyframeAnimations.degreeVec(0f, 0f, -12.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(0f, 17.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 0f, 12.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.12f, KeyframeAnimations.degreeVec(0f, -17.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
	public static final AnimationDefinition PENGUIN_FALLING = AnimationDefinition.Builder.withLength(3.72f)
			.addAnimation("penguin",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 3f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 3f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.88f, KeyframeAnimations.posVec(0f, -3.5f, -5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.posVec(0f, -3.5f, -5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.posVec(0f, -1f, -5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.posVec(0f, -1f, -5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("penguin",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.88f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fin_right",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.posVec(-1f, -1f, -3.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.posVec(-1f, -1f, -3.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.posVec(0f, -1f, -1.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.posVec(0f, -1f, -1.25f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fin_right",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(-115f, -115f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(-45f, -45f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.degreeVec(-115f, -115f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(-45f, -45f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(-115f, -115f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(-45f, -45f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(-115f, -115f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.88f, KeyframeAnimations.degreeVec(0f, -90f, -130f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, -90f, -130f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.degreeVec(-53f, -33.5f, -22.75f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.degreeVec(-53f, -33.5f, -22.75f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("feet_right",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, -0.25f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, -0.25f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.posVec(0f, 0f, -3.25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.posVec(0f, 0f, -3.25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.posVec(0f, -1f, -3.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.posVec(0f, -1f, -3.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("feet_right",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(55f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(55f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.degreeVec(65f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(65f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.degreeVec(105f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.degreeVec(105f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("feet_left",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.posVec(0f, 0f, -3.25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.posVec(0f, 0f, -3.25f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.posVec(0f, -1f, -3.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.posVec(0f, -1f, -3.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("feet_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(155f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(155f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.degreeVec(65f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(65f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.degreeVec(105f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.degreeVec(105f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fin_left",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.posVec(1f, -1f, -3.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.posVec(1f, -1f, -3.5f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.posVec(0f, -1f, -1.25f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.posVec(0f, -1f, -1.25f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fin_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 7.5f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(-115f, 115f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.32f, KeyframeAnimations.degreeVec(-45f, 45f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.4f, KeyframeAnimations.degreeVec(-115f, 115f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(-45f, 45f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.56f, KeyframeAnimations.degreeVec(-115f, 115f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.64f, KeyframeAnimations.degreeVec(-45f, 45f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(-115f, 115f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.88f, KeyframeAnimations.degreeVec(0f, 90f, 130f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 90f, 130f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.degreeVec(-53f, 33.5f, 22.75f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.degreeVec(-53f, 33.5f, 22.75f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.degreeVec(0f, 0f, 7.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("eyebrown_right",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.posVec(0f, 2f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.96f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("eyebrown_left",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.96f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.posVec(0f, -0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(2.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.96f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.72f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.88f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.96f, KeyframeAnimations.degreeVec(0f, -37.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.08f, KeyframeAnimations.degreeVec(0f, 15f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.16f, KeyframeAnimations.degreeVec(0f, -15f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.24f, KeyframeAnimations.degreeVec(0f, 15f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.32f, KeyframeAnimations.degreeVec(0f, -15f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.4f, KeyframeAnimations.degreeVec(0f, 15f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.degreeVec(0f, -15f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("eye_right",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.96f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("eye_right",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.scaleVec(1f, 2f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.scaleVec(1f, 2f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.scaleVec(1f, 2f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.96f, KeyframeAnimations.scaleVec(1f, 0.5f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.scaleVec(1f, 0.5f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("eye_left",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.96f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.posVec(0f, -0.25f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("eye_left",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.scaleVec(1f, 2f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.scaleVec(1f, 2f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.96f, KeyframeAnimations.scaleVec(1f, 0.5f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.scaleVec(1f, 0.5f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("pupil_right",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(0.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.posVec(0.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.96f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("pupil_right",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.scaleVec(0.5f, 0.25f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.scaleVec(0.5f, 0.25f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.scaleVec(0.5f, 0.25f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.96f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("pupil_left",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(-0.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.posVec(-0.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.posVec(-0.5f, -0.25f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.96f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("pupil_left",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.scaleVec(0.5f, 0.25f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.72f, KeyframeAnimations.scaleVec(0.5f, 0.25f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.88f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.56f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(2.8f, KeyframeAnimations.scaleVec(0.5f, 0.5f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(2.96f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.48f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.72f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
	public static final AnimationDefinition PENGUIN_JUMPING_INTO_THE_LAND = AnimationDefinition.Builder.withLength(3.36f)
			.addAnimation("penguin",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 3f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, -22f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 50f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.96f, KeyframeAnimations.posVec(0f, 50f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2f, KeyframeAnimations.posVec(0f, 2f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.posVec(0f, -3.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4f, KeyframeAnimations.posVec(0f, 1f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.56f, KeyframeAnimations.posVec(0f, -3.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.posVec(0f, -3.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.36f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("penguin",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(65f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(110f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2f, KeyframeAnimations.degreeVec(115f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(77.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.56f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.36f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("tail",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.36f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR)))
			.addAnimation("fin_right",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, -3f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.12f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.36f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fin_right",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-25f, -145f, -115f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(25f, 20f, -35f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, -90f, -90f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2f, KeyframeAnimations.degreeVec(0f, -90f, -90f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(-90f, -65f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(-90f, -115f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.56f, KeyframeAnimations.degreeVec(0f, -90f, -90f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.degreeVec(0f, -90f, -90f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.36f, KeyframeAnimations.degreeVec(0f, 0f, -7.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("feet_right",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.36f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("feet_right",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(135f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(115f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.56f, KeyframeAnimations.degreeVec(92.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.degreeVec(92.5f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.36f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("feet_left",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, -1f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.36f, KeyframeAnimations.posVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("feet_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(115f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.2f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(115f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.56f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.36f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fin_left",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, -3f, -1f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(3.12f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.36f, KeyframeAnimations.posVec(0f, 0.5f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("fin_left",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-25f, 145f, 115f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(25f, -20f, 35f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 90f, 90f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2f, KeyframeAnimations.degreeVec(0f, 90f, 90f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(-90f, 65f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(-90f, 115f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.56f, KeyframeAnimations.degreeVec(0f, 90f, 90f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.degreeVec(0f, 90f, 90f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.36f, KeyframeAnimations.degreeVec(0f, 0f, 7.5f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.POSITION,
							new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 3f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 3f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2f, KeyframeAnimations.posVec(0f, 3f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.posVec(0f, 1f, -3f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.56f, KeyframeAnimations.posVec(0f, 3f, -3f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.posVec(0f, 3f, -3f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.36f, KeyframeAnimations.posVec(0f, 0f, -2f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("head",
					new AnimationChannel(AnimationChannel.Targets.ROTATION,
							new Keyframe(0f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.24f, KeyframeAnimations.degreeVec(-125f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(0.48f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.2f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.28f, KeyframeAnimations.degreeVec(-97.5f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.4f, KeyframeAnimations.degreeVec(-65f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM),
							new Keyframe(1.56f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.12f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
									AnimationChannel.Interpolations.LINEAR),
							new Keyframe(3.36f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("eye_right",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(3.36f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM)))
			.addAnimation("eye_left",
					new AnimationChannel(AnimationChannel.Targets.SCALE,
							new Keyframe(3.36f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
									AnimationChannel.Interpolations.CATMULLROM))).build();
}